Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods

Metrics/MethodLength:
  Max: 99

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false